language: go
go:
  - 1.1x
services:
  - redis-server --port 6379
before_install:
  - go mod download
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci